### ISSUE TITLE
Review the Cadastre's approach to querying for parcels and/or the subgraph's architecture

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#268]
**Description**
The performance and stability of querying the subgraph for parcel shapes (paths of coordinates) are a challenge. We've implemented incremental fixes along the way (e.g. https://github.com/Geo-Web-Project/cadastre/pull/266 & https://github.com/Geo-Web-Project/cadastre/pull/176), but issues with **all parcels** promptly loading in the viewing window and **large parcels** loading fully persist. 

Per Cody's recommendation, let's go take a fresh look at our approach to loading parcel data and the structure of the index to see if we can get better reliability, performance, and scalability. 

Changes may be required on the Cadastre and/or the subgraph.

**Comment by codynhat** [comment]
Recording some brief thoughts here.

If we assume that all parcels are rectangles, we should be able to really improve the performance here. The subgraph currently indexes every `GeoWebCoordinate` and the cadastre queries for all coordinate nodes in the view. This initial design was mainly to support arbitrary shapes, not just rectangles. Instead of just indexing every coordinate we could also save two corners of a parcel. Then we only need to query for parcel nodes and not coordinates.

If scalability and performance is primarily a function of the number of nodes that need to be queried, this would drastically reduce the number of nodes by at least two orders of magnitude for most parcels.

My initial thought is this tradeoff of assuming rectangles is worth it for the performance and UX improvement. The smart contracts do not restrict parcels to rectangles, but the Cadastre does. Future cadastres could change this, or power users could claim non-rectangles through direct calls to the smart contract.

**Comment by gravenp** [comment]
That's a tempting option. Could there be a fallback of some kind for non-rectangles? I don't think we'd restrict ourselves to rectangles in the contracts (or know how that would be done). Having a known "edge case" failure doesn't feel good at all though. 

Could a different compression approach be to index/save each `GeoWebCoordinate` at a "change in direction" in the path (plus start & ending)?

**Comment by codynhat** [comment]
What do you mean by "change in direction"?

**Comment by gravenp** [comment]
Github isn't letting me upload images again for some reason. I sent you an image of what I'm thinking about if you want to upload it.

What I mean is if you draw an efficient path that touches every coordinate in a parcel, there will be stretches where that path is going in the same direction for multiple steps. If you omit those repeating steps in the index, the Cadastre can still recreate that full path (and arbitrary shapes) if you assume a line is drawn between each sequential coordinate in the list. 

A rectangle could be the top-left coordinate, the top-right coordinate, one row below the top-right coordinate, one row below the top-left coordinate, two rows below the top-left coordinate, two rows below the top-right coordinate, etc. There are other "compressed" ways to describe this pattern as well (coordinate, right 6, down 1, left 6, down 1, right 6 etc.)

The gains in efficiency depend on the shape and the chosen path, so there would be some best practices for how a path is initially defined in the claim I would think.

**Comment by codynhat** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/6885592/195931125-15188acf-d1af-457c-809e-0b5b91189f1d.png">

**Comment by codynhat** [comment]
Yea, similar idea just more complicated
