### ISSUE TITLE
Web3.storage pinning performance improvements

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#356]
Implement changes to improve the performance of pinning objects via the Media Gallery (like diff uploads only).

**Comment by codynhat** [comment]
There are two main pieces here.

1. Use the new [w3protocol](https://github.com/web3-storage/w3protocol) API w/ UCAN authentication
2. Only upload nodes that change

The new 1) API is needed to upload diffs. It also provides some other authentication benefits.

At a high-level, each change on `putPath` results in a new IPLD branch of the DAG that needs to be uploaded. The w3up APIs allow for a single CAR to be uploaded containing multiple CIDs. Using the [streaming API](https://github.com/web3-storage/w3protocol/tree/main/packages/upload-client#streaming-api) each node in the new branch can be indexed via the `store` service. Once the entire branch is traversed, all the nodes are uploaded as a single CAR using the `upload` service.

Elastic IPFS then serves each of these CIDs and can fetch them using byte ranges. Here are some great resources for leaning more about the uploads and how Elastic IPFS works.
- https://www.youtube.com/watch?v=A1c6JEEOgW4
- https://blog.web3.storage/posts/inside-the-galaxy%E2%80%99s-largest-ipfs-peer

**Comment by codynhat** [comment]
An intermediate step can be to use the existing Web3.storage CAR upload API, without the new w3protocol, which is still in beta.

This would not require integrating with UCAN, but would require a separate upload for each node in the branch instead of bundling them all into a single upload. The uploading would also use Web3.storage serverless workers instead of the direct uploading to a bucket, meaning less performance and reliability.
